name: pydev_conda
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.8.*
  - albumentations
  - numpy
  - matplotlib
  - opencv
  - tqdm
  - cudatoolkit
  - pytorch 
  - torchvision 
  - torchaudio 
  - jupyter
  - jupyterlab
  - jupytext
  - black
  - isort
  - autoflake
  - mock
  - mypy
  - pytest
  - ipywidgets
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jupyterlab_code_formatter
  - pip
  - pip:
    - lckr-jupyterlab-variableinspector
    - pytorch-pfn-extras
    - pytorch-ignite
    - mypy_ipython
